[package]
name = "pygarmin"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.128"
serde = { version = "1.0.209", features = ["derive"] }
chrono = "0.4.38"
tokio-postgres = "0.7.11"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }